### ISSUE TITLE
Debugging instructions for Code - OSS

### ISSUE THREAD

**Issue by di-effe** [vaxerski/Hypr#11]
Code OSS doesn´t have access to the full extension marketplace, so to be able to use cppdbg

- Download cpptools-linux.vsix from https://github.com/microsoft/vscode-cpptools/releases
- In vscode open the extentions panel
- Click on the dots in the top right corner
- Select install from vsix and select the downloaded package

**Comment by vaxerski** [comment]
I remember there was a way to unlock that in OSS, (because that's what I had done ages ago) but I can't find it right now.

I will add those instructions to the wiki, thanks.

**Comment by di-effe** [comment]
It's quite possibile there is a smarter way, I am not a developer :)

**Comment by vaxerski** [comment]
Added the instructions to the wiki. Thank you!
