### ISSUE TITLE
Config is not pre-installed, WM opens broken

### ISSUE THREAD

**Issue by indicozy** [vaxerski/Hypr#13]
Hi there! I watched your video on Reddit and gave it a try!

**Please describe the bug**
I followed all steps for building and adding to Xsessions, however when I start from SDDM, Arch Linux, nothing happens but there comes a black-ish bar on top of my SDDM. I guess that Hypr is trying to start some applications as picom, but fails.

**Steps to reproduce:**
Have a clean build of Arch + KDE, build Hypr, watch it failing to start

**Expected behavior**
Hypr starts successfully as expected

**Screenshots**
I will add in the reply

**Anything else?**
Also, is there any tutorial/wiki on hotkeys? I am a bit lost. I can contribute to wiki if that would be helpful

**Comment by indicozy** [comment]
![image](https://user-images.githubusercontent.com/51142471/144723274-8b12fa22-667e-4007-b6db-070e1f51fb02.png)

Bar on top is hardly visible, SDDM itself is unclickable, like it's an image. When I worked with other WMs, like BSPWM, an experience was similar. The bar comes in with an animation, slides down in about 0.5 seconds.

**Comment by vaxerski** [comment]
You need to start something. Xorg does NOT clean your desktop after you log in. With the default config, you have no keybinds. (I forgot to mention that, I should make it automatically use the example)

Paste the example config (/example/hypr.conf) into `~/.config/hypr/hypr.conf`

Press SUPER+ENTER to open xterm. It should pop up.

To set up a wallpaper, use something like `feh` or `nitrogen`. That will make your SDDM login screen disappear.

**Comment by vaxerski** [comment]
I have updated the wiki to explicitly say you need to copy the example config. I might make hypr generate a basic config in the future if none are found.

Please let me know if the instructions above fix your issue.

**Comment by indicozy** [comment]
> To set up a wallpaper, use something like `feh` or `nitrogen`. That will make your SDDM login screen disappear.

Thanks, I did that, but now I got another issue, I will open it
