### ISSUE TITLE
Hypr gets stuck on the login screen?

### ISSUE THREAD

**Issue by zleeepy** [vaxerski/Hypr#132]
When i select Hypr and login it just freezes and i have to reboot and go back to KDE. Does anyone know how to fix this?

**Comment by vaxerski** [comment]
have you tried just adding it to your xinitrc and using startx?

**Comment by zleeepy** [comment]
what's that?

**Comment by zleeepy** [comment]
i have no idea what any of that is @vaxerski

**Comment by zleeepy** [comment]
i fixed it but it is still frozen, i can exit hypr now although

**Comment by vaxerski** [comment]
> i have no idea what any of that is vaxerski

[duckduckgo.com](https://duckduckgo.com)

**Comment by zleeepy** [comment]
nvm got a diff gpu and ditched tiling
