### ISSUE TITLE
Keybinds for switching windows

### ISSUE THREAD

**Issue by Flammable-Duck** [vaxerski/Hypr#14]
**Is your feature request related to a problem? Please describe.**
When using a tiling window manager, I expect to be able to do everything through the keyboard, with the mouse being optional. Right now, according to the docs, you can only move windows with the keyboard, but must rely on the mouse to switch windows.

**Describe the solution you'd like**
Dispatchers for changing to the window above, below, left, and right of the currently active window. 

**Anything else?**
I also find the active window being switched by hovering over a window to be annoying, and  I would appreciate an option to disable it :D

**Comment by vaxerski** [comment]
sure

**Comment by vaxerski** [comment]
done with the last commit f83d3ccea72ba0f064b0f767196d5b494d9a41fb
