### ISSUE TITLE
Systray for WM

### ISSUE THREAD

**Issue by WitherCubes** [vaxerski/Hypr#15]
The title says it all, I don't know if there is already a way to have a systray, but if it isn't, please implement it.

**Comment by vaxerski** [comment]
there isn't one at the moment, sure, I can implement that into the bar :)

**Comment by WitherCubes** [comment]
Thank you, the only thing that is stopping me from trying out Hypr is the systray, I depend on it so much.

**Comment by vaxerski** [comment]
done in 2ca2ddfd2e9aed946c4de19bcc7e170023894c93
