### ISSUE TITLE
When the bar is disabled, fullscreen keybind lags

### ISSUE THREAD

**Issue by xqft** [vaxerski/Hypr#16]
**Please describe the bug**
Whenever the bar is disabled, there's a big delay (which varies from seconds to minutes) between pressing the key bind for fullscreen and the actual 'fullscreening' of the window. Sometimes the action doesn't even seem to apply (or the delay is too big).

**Steps to reproduce:**
- Set Bar { enabled = 0 } in the config
- Try to fullscreen windows multiple times

**Expected behavior**
That the action will be performed at the same time the key is pressed.

**Screenshots**
-

**Anything else?**
Log is cluttered with "Cairo is null but attempted to draw!", maybe that has something to do?

**Comment by vaxerski** [comment]
Oh shit that's my fault for sure alr. I'll look into that.
