### ISSUE TITLE
Can't re-attach tabs to brave browser windows

### ISSUE THREAD

**Issue by KieranCodes** [vaxerski/Hypr#21]
**Please describe the bug**
Can't re-attach tabs to brave browser windows, and when trying to reorder tabs, they pop out and make a new window.

**Steps to reproduce:**
Open two tabs in brave and try to rearrange them or connect them so they're in the same window.

**Comment by vaxerski** [comment]
tested with google chrome, I can see the issue, but looking at the logs I have no idea why. Firefox works.

I'll look into it.
