### ISSUE TITLE
Can't move focus to some windows

### ISSUE THREAD

**Issue by KieranCodes** [vaxerski/Hypr#26]
**Please describe the bug**
Can't move focus to some windows

**Steps to reproduce:**
Open four windows in a 2x2 grid and try to move the focus to each one using the keybindings

**Expected behavior**
The window gaining focus should be the nearest one to the old window. For example, if the bottom-left window has focus and I press ALT+L, the bottom-right window should gain focus. It seems to currently prioritise whichever window was opened first (which in this case is the top-right window).

**Comment by vaxerski** [comment]
fixed alongside other issues in b6fc46714fb6f3046312b6e64d809b51f3f1e482
