### ISSUE TITLE
Documentation issue.

### ISSUE THREAD

**Issue by rainwashed** [vaxerski/Hypr#27]
For the building of Hypr with the Ubuntu instructions (i run mint 20.2 which is basically ubuntu), the installation dependencies also require **build-essential**, otherwise a **CMAKE_CXX_COMPILER** error will occur. I recommend updating the dependency list to also include **build-essential**.

``sudo apt install xcb cmake gcc libgtk-3-dev ninja-build libgtkmm-3.0-dev libxcb-randr0 libxcb-randr0-dev libxcb-util-dev libxcb-util0-dev libxcb-util1 libxcb-ewmh-dev libxcb-xinerama0 libxcb-xinerama0-dev libxcb-icccm4-dev libxcb-keysyms1-dev libxcb-cursor-dev libxcb-shape0-dev build-essential``

```
CMake Error at CMakeLists.txt:2 (project):
  No CMAKE_CXX_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.
```

**Comment by vaxerski** [comment]
done. Thanks!
