### ISSUE TITLE
Missing documentation?

### ISSUE THREAD

**Issue by SisyphusIsntHappy** [vaxerski/Hypr#28]
I could not find documentation on keybindings, especially, quitting and reloading Hypr. Is there any? The example config doesn't have those bindings.

**Comment by linuxmobile** [comment]
> I could not find documentation on keybindings, especially, quitting and reloading Hypr. Is there any? The example config doesn't have those bindings.

I want to add something too. I can't find the way to add: Some rofi scripts, some shortcuts to notify-send.sh like: XF86AudioRaiseVolume(vol +) = command "bash -c '~/.scripts/notify/change-volume up"
XF86AudioLowerVolume (vol -)  = command "bash -c '~/.scripts/notify/change-volume down"
PRINT = bash -c '~/.scripts/shot-now'

More documentation can be perfect :)

**Comment by vaxerski** [comment]
Regarding the first comment:
There is no keybinding for reloading Hypr. What do you want to reload? The config gets reloaded automatically.

There is no keybinding for quitting hypr. Use bind=mod,key,exec,pkill Hypr


Regarding the second comment:
What are the commands here? those after bash -c? just put them in an exec bind:
bind=mod,key,exec,~/scripts/shot-now

The documentation mentions the exec dispatcher and it's also used in the example config.

**Comment by linuxmobile** [comment]
> Regarding the first comment: There is no keybinding for reloading Hypr. What do you want to reload? The config gets reloaded automatically.
> 
> There is no keybinding for quitting hypr. Use `bind=mod,key,exec,pkill Hypr`
> 
> Regarding the second comment: What are the commands here? those after bash -c? just put them in an exec bind: `bind=mod,key,exec,~/scripts/shot-now`
> 
> The documentation mentions the exec dispatcher and it's also used in the example config.

I can't get workin PRINT key, and a lot of .scripts can't run too.
same problem with `XF86AudioLowerVolume`  this keys... You can find my dotfiles in my user.

**Comment by SisyphusIsntHappy** [comment]
> There is no keybinding for quitting hypr. Use `bind=mod,key,exec,pkill Hypr`

Will `pkill Hypr` kill all the processes that were started by Hypr??

**Comment by vaxerski** [comment]
Print keys and the other ones aren't a feature. I can add that in. Regarding the scripts, it probably is an issue on your end. try absolute paths. 

Ad 2. `pkill Hypr` will make xorg exit, so probably yes.

**Comment by vaxerski** [comment]
Added support for all x keys in fa20d1342545f3b6871ffe6e2fba963cd8c595ad

Check your key's name with `xmodmap -pk` or `xev -event keyboard`, for prt scr it's "Print" (case-sensitive!)

**Comment by samwhelp** [comment]
> Added support for all x keys in [fa20d13](https://github.com/vaxerski/Hypr/commit/fa20d1342545f3b6871ffe6e2fba963cd8c595ad)
> 
> Check your key's name with `xmodmap -pk` or `xev -event keyboard`, for prt scr it's "Print" (case-sensitive!)

It works.

Please see my [hypr.conf](https://github.com/samwhelp/note-about-hyprwm/blob/gh-pages/_demo/config/hyprwm-config/basic/config/hypr/hypr.conf#L135).


## See Also
* demo [sxhkd-config](https://github.com/samwhelp/note-about-bspwm/tree/gh-pages/_demo/config/sxhkd-config)

**Comment by linuxmobile** [comment]
> Added support for all x keys in [fa20d13](https://github.com/vaxerski/Hypr/commit/fa20d1342545f3b6871ffe6e2fba963cd8c595ad)
> 
> Check your key's name with `xmodmap -pk` or `xev -event keyboard`, for prt scr it's "Print" (case-sensitive!)

Great. It works. Thx u a lot. This is an amazing project

**Comment by vaxerski** [comment]
Closing. Issue fixed and I've clarified it in the wiki that you do not reload hypr with a keybind and you exit with e.g. `pkill Hypr`.
