### ISSUE TITLE
Cannot connect to the X server.

### ISSUE THREAD

**Issue by Cenderme** [vaxerski/Hypr#29]
**Please describe the bug**
Cannot connect to the X server.

**Steps to reproduce:**
run `Hypr`

**Expected behavior**
Connect to the X server.

**[Log file:](https://ghostbin.com/blVwM)**
 [LOG] Hypr debug log. Built on Dec 26 2021 at 19:02:29
 [LOG] Pipes done! Forking!
 [LOG] Parent continuing!
 [CRITICAL] Connection Failed! Return: 5
 [LOG] Child says Hello World!
 [CRITICAL] Connection Failed! Return: 5
 [ERR] Bar exited with code 5!
[https://ghostbin.com/blVwM](https://ghostbin.com/blVwM)

**Comment by vaxerski** [comment]
`XCB_CONN_CLOSED_PARSE_ERR`

How are you launching the WM? What's the output of `echo $DISPLAY`, is it correct?

**Comment by Cenderme** [comment]
After I login to my account, I use `Hypr` to launch the WM. `echo $DISPLAY` outputs nothing. I tried to set it to :0 by running `DISPLAY=':0'` but it still gave the same error.

**Comment by vaxerski** [comment]
From what you're saying, I am guessing you are just launching `Hypr` from a tty. That's not the correct way to launch an Xorg WM. 

Put `exec Hypr` in `~/.xinitrc` and type `startx`.

**Comment by Cenderme** [comment]
Thank you. I'm a beginner to Linux. I didn't know that was the way to start window managers, Sorry for the trouble 😅.

But for some reason now I can't use keybindings. I'm just copying the example config from the repo to ~/.config/hypr/hypr.conf. When I change the config WM reloads and I can see the difference but keybindings won't work. I tried SUPER and ALT but to no avail.
[The log](https://ghostbin.com/50xpe)

**Comment by vaxerski** [comment]
restart xorg.
if that doesn't fix it, post your config.

**Comment by Cenderme** [comment]
https://ghostbin.com/E9zM6

**Comment by vaxerski** [comment]
That is very weird, I've never come across this. What it seems is happening (judging by the previous log) is that the WM doesn't recieve any key press events. I'll add some more logging and we'll see what happens.

**Comment by vaxerski** [comment]
recompile and try now, then show me the log. (Try to also hit stuff like super+r, super+q, super+g)

**Comment by Cenderme** [comment]
https://ghostbin.com/UwasW
The problem persists. Sadly, key combinations are not recognized by WM.

**Comment by vaxerski** [comment]
Something must be off on your end. Xorg doesn't recieve keyboard input. (or it doesn't pass it to the WM).

It does not seem like an issue with the window manager.

Try to disable all unnecessary stuff at X start.

also, add
```
exec-once=kitty
```
(kitty or your favorite terminal emulator)

and let me know if you can type inside it. If not, congrats, you found the issue. If yes, I have never seen such a weird bug.

**Comment by samwhelp** [comment]
> I pulled the latest commit from the repo and rebuilt it. The new log:
> https://ghostbin.com/UwasW

I guess it works on your system.

If you use example/[hypr.conf](https://github.com/vaxerski/Hypr/blob/main/example/hypr.conf#L70),

**there is no wallpper.**

You should start for your self.

You could use `Super + Enter` to launch `xterm`, if `xterm` on you system.

Then you could set wallpaper use `feh --bg-fill /usr/share/backgrounds/forest.jpg`


=============================================================================

If you want to autostart,

please see my [~/.config/hypr/hypr.conf](https://github.com/samwhelp/note-about-hyprwm/blob/gh-pages/_demo/config/hyprwm-config/basic/config/hypr/hypr.conf#L21) for reference.

I use `exec-once=~/.config/hypr/autostart`.

and see my [~/.config/hypr/autostart](https://github.com/samwhelp/note-about-hyprwm/blob/gh-pages/_demo/config/hyprwm-config/basic/config/hypr/autostart#L58).

search keyword: feh

**Comment by Cenderme** [comment]
> Try to disable all unnecessary stuff at X start.
weirdly, [_numlockx_](https://github.com/rg3/numlockx) was causing issues. I can successfully run the program without any errors but when I do, keybindings doesn't work. The program doesn't cause any problems with other window managers though. Weird... Thank you for your help. <3

@samwhelp Thanks for the advice!
