### ISSUE TITLE
Remove borders and gaps when only window in workspace

### ISSUE THREAD

**Issue by MoonKnight76** [vaxerski/Hypr#36]
**Describe the solution you'd like**
I really liked this feature in i3. Could use the fullscreen function but atleast in firefox the URL bar wil move up which is kind of annoying

**Comment by vaxerski** [comment]
what

so like... fullscreen without telling the app it's fullscreen? or should the bar be visible too?

**Comment by MoonKnight76** [comment]
Yeah like
Border_size, gaps_in and gaps_out all set to 0 when it is the only window on the monitor

**Comment by vaxerski** [comment]
added in 5d69be9a9894e13383b7c61c18dd042067dbf938

see the examples/hypr.conf or the wiki for how to enable the new functionality.

Thanks!
