### ISSUE TITLE
Resize  windows with mouse or keyboard combination

### ISSUE THREAD

**Issue by LucaErr** [vaxerski/Hypr#39]
# The problem and the solution
**I think the main feature that this wm doesn't have is the possibility to resize windows without any kind of window rule in hypr.conf.
Without this feature i can't use in the way i want my monitor, for exaple: in the same workspace i've got vs code and another application like telegram but don't want telegram taking half of the screen, just a little portion.**
like this:

                              
![Screenshot from 2022-03-10 00-18-18](https://user-images.githubusercontent.com/73197383/157556246-7422e5ac-b722-40f3-81d1-0582da1efe95.png)
                         

**Describe the solution you'd like**
I would like to see implemented in this wm an intuitive way to resize windows.

Hope everything is clear

**Comment by vaxerski** [comment]
You can resize them with the keyboard. See the `splitratio` dispatcher.

As for the mouse, it's on my todo list.

**Comment by vaxerski** [comment]
pull and recompile, it was added yesterday. (also it's only made for dwindling rn, not master)
