### ISSUE TITLE
Aur package crashes on startup, cloned repo doesnt

### ISSUE THREAD

**Issue by MoonKnight76** [vaxerski/Hypr#41]
**Please describe the bug**
When using the AUR version it crashes after startx

**Steps to reproduce:**
First remove the Hypr binary from /usr/bin and remove the desktop file from /usr/share/xsessions/ to avoid confusion and yay errors.
Use the example config.
My .xinitrc only contains the line "exec Hypr".

1.
yay -S hypr-git
startx

It crashes after the bar is loaded or, if disabled, after a window tries to start

2.
yay -Rns hypr-git
git clone git@github.com:vaxerski/Hypr
cd Hypr
make release
sudo cp build/Hypr /usr/bin/
startx

This version works completely normal

When it crashes xorg prints something along the lines of "Couldn't find gtk-theme" but because my resolution is fucked up part is printed off screen.
I couldn't find anything in both the Xorg log or the hypr log.

**Comment by vaxerski** [comment]
attach the hypr log regardless (of course if it exists)

post a stack trace
`coredumpctl`
and then
`coredumpctl info <pid>`

please remember the AUR package is _not_ maintained by me.

**Comment by LucaErr** [comment]
The aur package is out of date

**Comment by vaxerski** [comment]
it's a git package though, should fetch the last commit

**Comment by LucaErr** [comment]
Ik, but the aur package actually doesn't works.

**Comment by vaxerski** [comment]
oh shit you're right, the version it has is stuck at commit 255 and we're at 323 already

you've got to contact the author then
![image](https://user-images.githubusercontent.com/43317083/157964511-cc7bdc64-2c08-4ef7-988a-b4c983f5600f.png)

And for now I'll add a warning in the README. thanks!

**Comment by LucaErr** [comment]
No problem, i'll contact him as fast as possible.

**Comment by vaxerski** [comment]
thanks again!

**Comment by LucaErr** [comment]
i sent to him a mail, i'm waiting for response.

**Comment by vaxerski** [comment]
> attach the hypr log regardless (of course if it exists)
> 
> post a stack trace `coredumpctl` and then `coredumpctl info <pid>`

reopened, please provide more info.

**Comment by FryDay** [comment]
I'll monitor this thread as well in case there really is something messed up with the AUR package (I'm the maintainer), but as @vaxerski said, it IS up to date. Versions just don't appear to change for `-git` packages.

**Comment by LucaErr** [comment]
i want to confirm that what happened to @MoonKnight76  is allso happened to me. Sometimes even worse, i was able to enter to the wm but instantly it crashed (These things happened to me only with the aur package installed).

**Comment by vaxerski** [comment]
> i want to confirm that what happened to @MoonKnight76 is allso happened to me. Sometimes even worse, i was able to enter to the wm but instantly it crashed (These things happened to me only with the aur package installed).

come to think of it y'all are right as I did in fact had to build manually on my 10 year old laptop cuz the AUR pkg would crash. I blamed it on the laptop though

**Comment by FryDay** [comment]
I looked through the pkgbuild again. The only thing that stood out to me was a permission issue with the `.desktop` file (it was being marked as executable). I don't think that would cause the issues that you all are describing, but it's fixed anyway.

**Comment by vaxerski** [comment]
Nope, didn't fix.

Stacktrace:
```
Stack trace of thread 1041668:
                #0  0x00007f0d9db7934c __pthread_kill_implementation (libc.so.6 + 0x8f34c)
                #1  0x00007f0d9db2c4b8 raise (libc.so.6 + 0x424b8)
                #2  0x00007f0d9db16534 abort (libc.so.6 + 0x2c534)
                #3  0x000000000041ec7e n/a (Hypr + 0x1ec7e)
                #4  0x000000000044e097 n/a (Hypr + 0x4e097)
                #5  0x0000000000469a0b n/a (Hypr + 0x69a0b)
                #6  0x000000000046cdd2 n/a (Hypr + 0x6cdd2)
                #7  0x000000000040f421 n/a (Hypr + 0xf421)
                #8  0x00007f0d9db17310 __libc_start_call_main (libc.so.6 + 0x2d310)
                #9  0x00007f0d9db173c1 __libc_start_main@@GLIBC_2.34 (libc.so.6 + 0x2d3c1)
                #10 0x0000000000413df5 n/a (Hypr + 0x13df5)
                
                Stack trace of thread 1041862:
                #0  0x00007f0d9dbc2a55 clock_nanosleep@GLIBC_2.2.5 (libc.so.6 + 0xd8a55)
                #1  0x00007f0d9dbc7717 __nanosleep (libc.so.6 + 0xdd717)
                #2  0x000000000043fb27 n/a (Hypr + 0x3fb27)
                #3  0x00007f0d9e0a3815 n/a (libglib-2.0.so.0 + 0x84815)
                #4  0x00007f0d9db775c2 start_thread (libc.so.6 + 0x8d5c2)
                #5  0x00007f0d9dbfc584 __clone (libc.so.6 + 0x112584)
                ELF object binary architecture: AMD x86-64
```

Very weird, that's when compiling with debug.

`Signal: 6 (ABRT)`
is suspicious

**Comment by FryDay** [comment]
I just removed Hypr from my system entirely and rebuilt from the AUR and can confirm I am getting the same errors now.

```
Stack trace of thread 944606:
                #0  0x00007f72b8da634c __pthread_kill_implementation (libc.so.6 + 0x8f34c)
                #1  0x00007f72b8d594b8 raise (libc.so.6 + 0x424b8)
                #2  0x00007f72b8d43534 abort (libc.so.6 + 0x2c534)
                #3  0x000055d58baada4a n/a (Hypr + 0x27a4a)
                #4  0x000055d58badf0fa n/a (Hypr + 0x590fa)
                #5  0x000055d58badad4d n/a (Hypr + 0x54d4d)
                #6  0x000055d58bafccdd n/a (Hypr + 0x76cdd)
                #7  0x000055d58bb04522 n/a (Hypr + 0x7e522)
                #8  0x000055d58ba9c06a n/a (Hypr + 0x1606a)
                #9  0x00007f72b8d44310 __libc_start_call_main (libc.so.6 + 0x2d310)
                #10 0x00007f72b8d443c1 __libc_start_main@@GLIBC_2.34 (libc.so.6 + 0x2d3c1)
                #11 0x000055d58baa0d65 n/a (Hypr + 0x1ad65)

                Stack trace of thread 944695:
                #0  0x00007f72b8defa55 clock_nanosleep@GLIBC_2.2.5 (libc.so.6 + 0xd8a55)
                #1  0x00007f72b8df4717 __nanosleep (libc.so.6 + 0xdd717)
                #2  0x000055d58bad0987 n/a (Hypr + 0x4a987)
                #3  0x00007f72b92d0815 n/a (libglib-2.0.so.0 + 0x84815)
                #4  0x00007f72b8da45c2 start_thread (libc.so.6 + 0x8d5c2)
                #5  0x00007f72b8e29584 __clone (libc.so.6 + 0x112584)
                ELF object binary architecture: AMD x86-64
```

**Comment by vaxerski** [comment]
Build probably missing a dep for pthreads or something, I know a friend of mine had to add another dep on void. Maybe try adding glibc to the deps?

**Comment by FryDay** [comment]
If it were a missing dep, manually building the git package would also result in a bad binary.

**Comment by vaxerski** [comment]
I can't think of anything else. `makepkg` does build in some sort of encapsulation, doesn't it?

**Comment by FryDay** [comment]
That's possible. Give me a little bit to test.

**Comment by vaxerski** [comment]
tried with `make PREFIX="/usr" SYSCONFDIR="/etc" release` and still broken.

On a side note: you should consider adding an install -Dm644 for the example config too, as the window manager is kind of unusable without one and it'd be nice to provide a default config automatically.

**Comment by FryDay** [comment]
If I did that, it would override changes made to your config.

**Comment by vaxerski** [comment]
Oh, okay, fair. If there's no way to "install only if doesn't exist" then yeah, fair.

**Comment by FryDay** [comment]
I could probably write it out if it doesn't exist, but if you make a breaking change to the config, there will need to be manual intervention anyway. At this point I'm just trying to get it to work :D

**Comment by FryDay** [comment]
Alright everybody, I just pushed a fix to the AUR package. Please rebuild and see if it fixes it for you.

**Comment by vaxerski** [comment]
Seems fixed for me, closing.

Thanks!
