### ISSUE TITLE
AUR Package

### ISSUE THREAD

**Issue by FryDay** [vaxerski/Hypr#42]
I'm the maintainer of hypr-git in the AUR and saw the note in the README about being out of date (as well as receiving a few emails). With -git packages in the AUR, it is expected that the latest revision be pulled when the package is built, which is how it is currently setup. The revision on the aur page does not change, but the latest code is always pulled. See [here](https://wiki.archlinux.org/title/Arch_User_Repository#What_is_the_difference_between_foo_and_foo-git_packages?) for more details.

**Comment by vaxerski** [comment]
@MoonKnight76 reported in #41 that it's broken. Cloning the repo works, the package doesn't.

I can see that the version is updated when doing a `yay -S` okay, false alarm.

Issue #41 persists still then, reopening that.
