### ISSUE TITLE
[Documentation]

### ISSUE THREAD

**Issue by jzbor** [vaxerski/Hypr#45]
Is Hypr a compositing window manager? Does it make compositors such as picom obsolete? It would me nice if those things would be documented somewhere. Thanks a lot for the project - it looks great!

**Comment by vaxerski** [comment]
No, Hypr is _only_ a window manager. It runs on Xorg, so technically a compositor is not necessary, however, Hypr does not replace nor implement functionality provided by a compositor.

Rounded corners and animations are done properly from within the window manager, and not through a compositor.
