### ISSUE TITLE
Keybinds are not applied

### ISSUE THREAD

**Issue by BeZaBel** [vaxerski/Hypr#48]
**Please describe the bug**
When starting Hypr the config file is loaded fine, my execs work just fine, but the keybinds are not working. I made an exec to start a terminal at launch and be able to interact with Hypr. Checking the debug log it says that the keybinds are not applied because the status bar is not null (see the log).

**Steps to reproduce:**
Just launching Hypr normally through SDDM. I am installing Hypr through the AUR package in Arch Linux.

**Expected behavior**
Keybinds loaded so it is usable.

**Log:**
https://pastebin.com/pdPywPde

**Comment by vaxerski** [comment]
> Checking the debug log it says that the keybinds are not applied because the status bar is not null
that is correct and expected behavior. Attach your hypr.conf please

**Comment by BeZaBel** [comment]
Here is my config file. Is just a slight modification of the example file.

https://pastebin.com/JhPhsUbx

**Comment by vaxerski** [comment]
Your keybinds are being applied:

```
[LOG] Reloading the config!
[LOG] Applying 4 keybinds to X.
[LOG] Applying 4 keybinds to X.
```

You most likely are missing `xmodmap` installed :P

**Comment by BeZaBel** [comment]
I have installed `xmodmap` and the problem still persists. I think it is somehow related with the mapping on my keyboard because messing with it breaks sometimes i3 too. Nonetheless, I can't get any mod key to work. Neither Alt, Ctrl or Shift.

**Comment by vaxerski** [comment]
do you get the correct amount of keybinds applied? it should say in the log.

Try turning off any other mods, for example scroll lock, which is a common oopsie people make.

**Comment by not-NEKO** [comment]
i had the same problem

**Comment by vaxerski** [comment]
> to fix it just remove the , at the end

at the end of...? I don't see where the config is wrong, and the logs don't show anything out of the ordinary

> (make a discord server pls)

what for? spam and trolls?

**Comment by not-NEKO** [comment]
at the end of some keybind there is some time a , i don't know why but i just removed it and now it works

**Comment by vaxerski** [comment]
> at the end of some keybind there is some time a , i don't know why but i just removed it and now it works

idk how as it _should_ be there, but okaay

it signifies an empty argument

**Comment by jkim5959** [comment]
I have similar problem too. Weird thing is, it works at first but then after some minutes it suddenly doesn't work. None of the key bindings. I do have xmodmap installed.

I will try removing ,s soon tho.

**Comment by vaxerski** [comment]
oh god not debian

it might be, highly probable.

If you can, see what the config says when keybinds go dead. You can use 
```
watch -n 0.3 "cat /tmp/hypr/hypr.log | grep -v \"dirty\" | grep -v \"nimation\" | tail -n 40"
```
to watch the config in real time with only the meaningful logs

**Comment by BeZaBel** [comment]
> Try turning off any other mods, for example scroll lock, which is a common oopsie people make.

I turned it off and now everything works! Thanks!

**Comment by vaxerski** [comment]
closing then, cheers.

**Comment by vaxerski** [comment]
> (make a discord server pls)

ok, i made it
