### ISSUE TITLE
Allow pinning a floating window so it appears on all workspaces.

### ISSUE THREAD

**Issue by mk1923** [vaxerski/Hypr#54]
Bspwm allows pinning a floating window so it appears on all workspaces/travels with you when you switch. This is very useful when you're, for example, watching something in mpv whilst doing something else. I like to keep mpv open in a floating, smaller window, whilst working on something. Being able to pin it so it follows me when I switch workspaces and have it appear always on top/above other windows is wonderful. Similar to picture-in-picture on televisions.

**Comment by vaxerski** [comment]
added in 83d69cb233288a95d79bc5ae97c14e405e414c3a

**Comment by vaxerski** [comment]
pin dispatcher. it's on the wiki

**Comment by mk1923** [comment]
Thanks, that works. I don't think it is in the wiki, though. At least I can't see it in the dispatcher list.

**Comment by vaxerski** [comment]
fixed
