### ISSUE TITLE
When numlock is on, key bindings don't work.

### ISSUE THREAD

**Issue by kanibusrex** [vaxerski/Hypr#58]
When numlock is on, the key bindings don't work. I currently have the super key as the mod key.

**Comment by vaxerski** [comment]
yes, that's how mods work. numlock, scrolllock, caps lock are all mods. What do you want me to do?

**Comment by kanibusrex** [comment]
So, if I’m working on a spreadsheet, and I’m using the number pad, and I need to open another app. I have to turn off numlock, hit Super+D for dmenu, open the app, then turn numlock on again. I just wasn’t aware that numlock affected the super key.

**Comment by vaxerski** [comment]
added an option to ignore mod in 3518e3ba8aa43e759ad7c65142ebdd328549c967

use
```
ignore_mod=MOD
```
to ignore a mod, you have a list in the wiki.

If none of the mods work, you can use a mask (e.g. 256) that corresponds to the scroll lock or whatever key you want to be ignored.

**Comment by kanibusrex** [comment]
Thank you. That did the trick. 
vaxerski wrote:
added an option to ignore mod in 3518e3b <https://github.com/vaxerski/Hypr/commit/3518e3ba8aa43e759ad7c65142ebdd328549c967> 
use
ignore_mod=MOD 
to ignore a mod, you have a list in the wiki.
If none of the mods work, you can use a mask (e.g. 256) that corresponds to the scroll lock or whatever key you want to be ignored.
