### ISSUE TITLE
Polybar problems with the bar location

### ISSUE THREAD

**Issue by LucaErr** [vaxerski/Hypr#59]
The video perfectly explain the problem.
 The only thing that i do is starting my dock.

LATEST HYPRWM VER 
LATEST POLYBAR-GIT VER

https://user-images.githubusercontent.com/73197383/162636383-fe904b06-6396-491f-b034-ac9d3737ce81.mov

if more details are needed i could provide them

**Comment by vaxerski** [comment]
as usual, please provide your polybar config as my polybar has been working perfectly fine

**Comment by LucaErr** [comment]
[here](https://pastebin.com/EPCe4zKt)

**Comment by LucaErr** [comment]
[hypr.log](https://pastebin.com/NP5u8h5k)

**Comment by vaxerski** [comment]
![20220411_19h25m35s_grim](https://user-images.githubusercontent.com/43317083/162795858-cfc24fc4-2e21-4742-8700-ed6638522642.png)

config issue. a rule is moving it.

**Comment by LucaErr** [comment]
solved thanks.
i remove `windowrule=size 500 50,class:krunner
`
