### ISSUE TITLE
[Bug] Using keycombos inputs text into active window

### ISSUE THREAD

**Issue by ExperiBass** [vaxerski/Hypr#61]
**Please describe the bug**
When using a key combo such as SUPER+V, text is input into the active window (if it allows for text input), but only if said keycombo doesn't switch workspaces.

**Steps to reproduce:**
1. Open a notepad or terminal.
2. Hit a key combo that doesn't change workspaces. I'm using SUPER+V.
3. See text.

**Expected behavior**
No text is input.

**Screenshots**
My screen recorder has decided not to work.

**Log:**
Please attach a log. (paste it into pastebin and paste here the url) The log can be found in a temp file located in /tmp/hypr/hypr.log.
[Too large to be put into pastebin](https://github.com/vaxerski/Hypr/files/8470223/hyprlog.txt)

**Comment by vaxerski** [comment]
Should not happen if the said keycombo is a keybind. If it is not, then yes, that's how keyboards work.

Will investigate once I get back home.

**Comment by ExperiBass** [comment]
said keycombo is a keybind, it alternates between horizontal and vertical stacking.

**Comment by vaxerski** [comment]
oh that's weird then, I'll see when I get back home

**Comment by vaxerski** [comment]
some possible keybind issues have been fixed in 1667180ac3554cdeaf00ac2cd0f3ad37e64bce30, check if this still occurs

**Comment by devraza** [comment]
I've been having the same issue, I changed the keybind from:
```
bind=SUPER,Q,exec,kitty
```
to:
```
bind=ALT,Q,exec,kitty
```
That somehow managed to fix the issue with launching kitty. (In short, using SUPER in keybindings doesn't work)

**Comment by devraza** [comment]
Nevermind, I somehow fixed the issue (probably by killing `sxhkd`)

**Comment by vaxerski** [comment]
killing a separate keybind daemon should probably be a good idea.

**Comment by ExperiBass** [comment]
Ok so good news and bad news

Good news: it works, I can use supershift now :D

Bad news: It also seems to have blocked keyboard input? I can use keybinding just fine, but I can't actually type anything.

**Comment by vaxerski** [comment]
make sure you didn't toggle scroll lock, or num lock or other of those

**Comment by vaxerski** [comment]
> workspaces or move windows to a different workspace.

yes I am an idiot fixed that one

**Comment by ExperiBass** [comment]
> make sure you didn't toggle scroll lock, or num lock or other of those

I'm 90% sure they're off, I don't have those keys

**Comment by vaxerski** [comment]
then come once again, what's the issue right now? You can't type in a window, e.g. a terminal?

**Comment by ExperiBass** [comment]
It looks like your workspace change fixed whatever was causing it, i can type just fine now. Original issue wasn't fixed though, SUPER+V still inputs `v` into vscode.

**Comment by vaxerski** [comment]
output of `xmodmap -pk | grep "V"`?

**Comment by ExperiBass** [comment]
`55    	0x0076 (v)	0x0056 (V)	0x0076 (v)	0x0056 (V)`

**Comment by vaxerski** [comment]
is 0x76 the correct keysym when you try `xev`? if not, your keyboard layout is haunted and you have to use the keysyms instead of letters.

**Comment by ExperiBass** [comment]
keysym is 0x76, time to call the ghostbusters

**Comment by vaxerski** [comment]
use the keysym manually then. Remember to convert the hex to dec when inputting in the config.

**Comment by ExperiBass** [comment]
yeah that works, thanks :D
