### ISSUE TITLE
Can't move windows or move them to other workspaces with SUPERSHIFT

### ISSUE THREAD

**Issue by Ozymptin** [vaxerski/Hypr#62]
**Please describe the bug**
When trying to move a window with the `movewindow` or `movetoworkspace` dispatcher, only the focus changes but the windows don't move. The last commit broke it.

Other keybinds like `SUPERSHIFT,Q,killactive` and `SUPER,F,fullscreen` do still work so SUPERSHIFT does work.

**Steps to reproduce:**
Use my config and try to move a window with `SUPERSHIFT + (left|right|up|down)` or try to move it to another workspace with `SUPERSHIFT + (1|2|3)`

[config](https://pastebin.com/DTQWxQNT)

**Comment by vaxerski** [comment]
> The last commit broke it.


FUCK

**Comment by vaxerski** [comment]
fixed in 1667180ac3554cdeaf00ac2cd0f3ad37e64bce30
