### ISSUE TITLE
Missing Packages

### ISSUE THREAD

**Issue by alexthotse** [vaxerski/Hypr#66]
Hey bro, I successfully installed all the packages you recommended(Wiki-Ubuntu).
I'm using Zorin 
![image](https://user-images.githubusercontent.com/30655517/163747291-d3acfbc8-711f-45ad-989c-48224f84550c.png)

Here is the error I'm getting. 
![image](https://user-images.githubusercontent.com/30655517/163747066-33607ddf-27cd-4f8b-a1a3-d2790a4700d4.png)

Trying to get the missing packages:
![image](https://user-images.githubusercontent.com/30655517/163747617-8f73b66f-d366-4442-97db-37b45db9e33d.png)

I'll try to fix it on my side and update you.

**Comment by alexthotse** [comment]
Update:

- xcb-icccm

![image](https://user-images.githubusercontent.com/30655517/163748171-d3da3e2c-39b3-4be4-bde8-2aac35643d04.png)

- xcb-keysyms

![image](https://user-images.githubusercontent.com/30655517/163748231-75a0721c-d6bf-46cf-a4e3-e40f95b7841a.png)

- xcb-cursor

![image](https://user-images.githubusercontent.com/30655517/163748366-226a96a0-c179-4a4e-8b8b-81c336083b29.png)

- xcb-ewmh

![image](https://user-images.githubusercontent.com/30655517/163748398-de15b0b9-765d-4849-9f60-a749602ea5c0.png)

- gtkmm-3.0

![image](https://user-images.githubusercontent.com/30655517/163748472-b7413cef-ea9e-4529-b5ff-3c0d5014dcd7.png)

**Comment by alexthotse** [comment]
Cario is too long but here is it anyways...


### sudo apt search cairo                                                                            100 ↵ ──(Mon,Apr18)─┘
- Sorting... Done
- Full Text Search... Done
## aghermann/focal 1.1.2-3build1 amd64
  - Sleep-research experiment manager

### cairo-5c/focal,focal 1.20+nmu1 all
  - nickle bindings for the cairo graphics library

### cairo-dock/focal 3.4.1-3 amd64
  - Metapackage for cairo-dock

### cairo-dock-alsamixer-plug-in/focal 3.4.1-6 amd64
  - Alsamixer plug-in for Cairo-dock

### cairo-dock-animated-icons-plug-in/focal 3.4.1-6 amd64
  - Animated icons plug-in Cairo-dock

### cairo-dock-cairo-penguin-plug-in/focal 3.4.1-6 amd64
  - Cairo-Penguin plug-in for Cairo-dock

### cairo-dock-clipper-plug-in/focal 3.4.1-6 amd64
  - Clipper plug-in for Cairo-dock

### cairo-dock-clock-plug-in/focal 3.4.1-6 amd64
  - Clock plug-in for Cairo-dock

### cairo-dock-core/focal 3.4.1-3 amd64
  - Light eye-candy fully themable animated dock for Linux desktop

### cairo-dock-dbus-plug-in/focal 3.4.1-6 amd64
  - Dbus plug-in for Cairo-dock

### cairo-dock-dbus-plug-in-interface-mono/focal 3.4.1-6 amd64
  - library of D-Bus interface for mono of Cairo-dock

### cairo-dock-dbus-plug-in-interface-python/focal,focal 3.4.1-6 all
  - library of D-Bus interface for Python of Cairo-dock

### cairo-dock-dbus-plug-in-interface-ruby/focal,focal 3.4.1-6 all
  - library of D-Bus interface for ruby of Cairo-dock

### cairo-dock-dbus-plug-in-interface-vala/focal 3.4.1-6 amd64
  - library of D-Bus interface for vala of Cairo-dock

### cairo-dock-desklet-rendering-plug-in/focal 3.4.1-6 amd64
  - Desklet rendering plug-in for Cairo-dock

### cairo-dock-dev/focal 3.4.1-3 amd64
  - Cairo-dock development file

### cairo-dock-dialog-rendering-plug-in/focal 3.4.1-6 amd64
  - Dialog rendering plug-in for Cairo-dock

### cairo-dock-dnd2share-plug-in/focal 3.4.1-6 amd64
  - Dnd2share plug-in for Cairo-dock

### cairo-dock-drop-indicator-plug-in/focal 3.4.1-6 amd64
  - Drop indicator plug-in for Cairo-dock

### cairo-dock-dustbin-plug-in/focal 3.4.1-6 amd64
  - Dustbin plug-in for Cairo-dock

### cairo-dock-folders-plug-in/focal 3.4.1-6 amd64
  - Folders plug-in Cairo-dock

### cairo-dock-gmenu-plug-in/focal 3.4.1-6 amd64
  - GMenu plug-in for Cairo-dock

### cairo-dock-gnome-integration-plug-in/focal 3.4.1-6 amd64
  - GNOME integration plug-in for Cairo-dock

### cairo-dock-icon-effect-plug-in/focal 3.4.1-6 amd64
  - Icon effect plug-in for Cairo-dock

### cairo-dock-illusion-plug-in/focal 3.4.1-6 amd64
  - Illusion plug-in for Cairo-dock

### cairo-dock-impulse-plug-in/focal 3.4.1-6 amd64
  - Implus plug-in Cairo-dock

### cairo-dock-kde-integration-plug-in/focal 3.4.1-6 amd64
  - KDE integration plug-in for Cairo-dock

### cairo-dock-keyboard-indicator-plug-in/focal 3.4.1-6 amd64
  - Keyboard indicator plug-in for Cairo-dock

### cairo-dock-logout-plug-in/focal 3.4.1-6 amd64
  - Logout plug-in for Cairo-dock

### cairo-dock-mail-plug-in/focal 3.4.1-6 amd64
  - Mail plug-in for Cairo-dock

### cairo-dock-messaging-menu-plug-in/focal 3.4.1-6 amd64
  - Messaging menu plug-in Cairo-dock

### cairo-dock-motion-blur-plug-in/focal 3.4.1-6 amd64
  - Motion blur plug-in for Cairo-dock

### cairo-dock-musicplayer-plug-in/focal 3.4.1-6 amd64
  - Music player plug-in for Cairo-dock

### cairo-dock-netspeed-plug-in/focal 3.4.1-6 amd64
  - Netspeed plug-in for Cairo-dock

### cairo-dock-plug-in-data/focal,focal 3.4.1-6 all
  - Cairo-dock - Plug-in data files

### cairo-dock-plug-ins/focal 3.4.1-6 amd64
  - Cairo-dock - All plug-ins

### cairo-dock-powermanager-plug-in/focal 3.4.1-6 amd64
  - Powermanager plug-in for Cairo-dock

### cairo-dock-quick-browser-plug-in/focal 3.4.1-6 amd64
  - Quick browser plug-in for Cairo-dock

### cairo-dock-recent-events-plug-in/focal 3.4.1-6 amd64
  - Recent events plug-in for Cairo-dock

### cairo-dock-remote-control-plug-in/focal 3.4.1-6 amd64
  - Remote control plug-in for Cairo-dock

### cairo-dock-rendering-plug-in/focal 3.4.1-6 amd64
  - Rendering plug-in for Cairo-dock

### cairo-dock-rssreader-plug-in/focal 3.4.1-6 amd64
  - RSS Reader plug-in for Cairo-dock

### cairo-dock-shortcuts-plug-in/focal 3.4.1-6 amd64
  - Shortcuts plug-in for Cairo-dock

### cairo-dock-showdesktop-plug-in/focal 3.4.1-6 amd64
  - Show desktop plug-in for Cairo-dock

### cairo-dock-showmouse-plug-in/focal 3.4.1-6 amd64
  - Showmouse plug-in Cairo-dock

### cairo-dock-slider-plug-in/focal 3.4.1-6 amd64
  - Slider plug-in Cairo-dock

### cairo-dock-stack-plug-in/focal 3.4.1-6 amd64
  - Stack plug-in for Cairo-dock

### cairo-dock-switcher-plug-in/focal 3.4.1-6 amd64
  - Switcher plug-in for Cairo-dock

### cairo-dock-system-monitor-plug-in/focal 3.4.1-6 amd64
  - System Monitor plug-in for Cairo-dock

### cairo-dock-systray-plug-in/focal 3.4.1-6 amd64
  - Systray plug-in for Cairo-dock

### cairo-dock-terminal-plug-in/focal 3.4.1-6 amd64
  - Terminal plug-in for Cairo-dock

### cairo-dock-tomboy-plug-in/focal 3.4.1-6 amd64
  - Tomboy plug-in for Cairo-dock

### cairo-dock-toons-plug-in/focal 3.4.1-6 amd64
  - Toons plug-in for Cairo-dock

### cairo-dock-weather-plug-in/focal 3.4.1-6 amd64
  - Weather plug-in for Cairo-dock

### cairo-dock-wifi-plug-in/focal 3.4.1-6 amd64
  - Wifi plug-in for Cairo-dock

### cairo-dock-xfce-integration-plug-in/focal 3.4.1-6 amd64
  - Xfce integration plug-in for Cairo-dock

### cairo-dock-xgamma-plug-in/focal 3.4.1-6 amd64
  - Xgamma plug-in for Cairo-dock

### cairo-perf-utils/focal 1.16.0-4ubuntu1 amd64
  - Cairo 2D vector graphics library performance utilities

### cairosvg/focal,focal 2.4.2-1 all
  - SVG to PDF/PS/PNG converter based on Cairo

### conky-all/focal 1.10.8-1build3 amd64
  - highly configurable system monitor (all features enabled)

### conky-all-dbg/focal 1.10.8-1build3 amd64
  - highly configurable system monitor (all features enabled - debug)

### darktable/focal 3.0.1-0ubuntu1 amd64
  - virtual lighttable and darkroom for photographers

### fcitx-ui-light/focal 0.1.3-3 amd64
  - light weight xlibs and xft based UI for Fcitx

### fdclock/focal 0.1.0+git.20060122-0ubuntu4 amd64
  - freedesktop.org clock

### fonts-hosny-amiri/focal,focal 0.112-2 all
  - Arabic Naskh style typographically oriented font

### fp-units-gfx/focal 3.0.4+dfsg-23 amd64
  - Free Pascal - graphics-library units dependency package

### fp-units-gfx-3.0.4/focal 3.0.4+dfsg-23 amd64
  - Free Pascal - graphics-library units

### gambas3-gb-cairo/focal 3.14.3-2ubuntu3.1 amd64
  - Gambas bindings for cairo

### gir1.2-freedesktop/focal-updates,now 1.64.1-1~ubuntu20.04.1 amd64 [installed,automatic]
  - Introspection data for some FreeDesktop components

### gir1.2-goocanvas-2.0/focal 2.0.4-1 amd64
  - GObject introspection data for GooCanvas - gir bindings

### giza-dev/focal 1.1.0-1 amd64
  - Lightweight scientific plotting library (development files)

### gnome-twitch-player-backend-gstreamer-cairo/focal 0.4.1-3 amd64
  - Player backend for GNOME Twitch based on gstreamer+cairo

### gnustep-back0.27-cairo/focal 0.27.0-2build1 amd64
  - GNUstep GUI Backend (cairo)

### golang-github-gotk3-gotk3-dev/focal,focal 0.0~GOTK3~0~2~0+git20170418.0.96d4110-3 all
  - Go bindings for GTK3

### gtk2-engines-murrine/focal,now 0.98.2-3 amd64 [installed,automatic]
  - cairo-based gtk+-2.0 theme engine

### guile-cairo/focal 1.10.0-5 amd64
  - Guile bindings for Cairo

### guile-cairo-dev/focal 1.10.0-5 amd64
  - Guile bindings for Cairo, development files

### lib2geom-dev/focal-backports 1.1-2~bpo20.04.1 amd64
  - robust computational geometry framework -- development library

### lib2geom1.1.0/focal-backports 1.1-2~bpo20.04.1 amd64
  - robust computational geometry framework -- shared library

### libaosd-dev/focal 0.2.7-1.1ubuntu2 amd64
  - atheme.org's on screen display library - dev

### libaosd-text2/focal 0.2.7-1.1ubuntu2 amd64
  - atheme.org's on screen display library - text layout

### libaosd2/focal 0.2.7-1.1ubuntu2 amd64
  - atheme.org's on screen display library - main

### libcairo-5c-dev/focal 1.20+nmu1 amd64
  - library for cairo nickle bindings dev files

### libcairo-5c0/focal 1.20+nmu1 amd64
  - library for cairo nickle bindings

### libcairo-gobject-perl/focal,now 1.005-2 amd64 [installed,automatic]
  - integrate Cairo into the Glib type system in Perl

### libcairo-gobject2/focal,now 1.16.0-4ubuntu1 amd64 [installed,automatic]
  - Cairo 2D vector graphics library (GObject library)

### libcairo-ocaml/focal 1:1.2.0-8build1 amd64
  - OCaml bindings for Cairo (runtime)

### libcairo-ocaml-dev/focal 1:1.2.0-8build1 amd64
  - OCaml bindings for Cairo

### libcairo-perl/focal,now 1.107-1 amd64 [installed,automatic]
  - Perl interface to the Cairo graphics library

### libcairo-script-interpreter2/focal,now 1.16.0-4ubuntu1 amd64 [installed,automatic]
  - Cairo 2D vector graphics library (script interpreter)

### libcairo1.10-cil/focal 2.99.3-4 amd64
  - CLI binding for Cairo

### ### libcairo2/focal,now 1.16.0-4ubuntu1 amd64 [installed,automatic]
  - Cairo 2D vector graphics library

### libcairo2-dev/focal,now 1.16.0-4ubuntu1 amd64 [installed,automatic]
  - Development files for the Cairo 2D graphics library

### libcairo2-doc/focal,focal 1.16.0-4ubuntu1 all
  - Documentation for the Cairo Multi-platform 2D graphics library

### libcairo2-ocaml/focal 0.6.1+dfsg-3 amd64
  - OCaml binding for Cairo (runtime library)

### libcairo2-ocaml-dev/focal 0.6.1+dfsg-3 amd64
  - OCaml binding for Cairo (development files)

### libcairomm-1.0-1v5/focal,now 1.12.2-4build1 amd64 [installed,automatic]
  - C++ wrappers for Cairo (shared libraries)

### libcairomm-1.0-dev/focal,now 1.12.2-4build1 amd64 [installed,automatic]
  - C++ wrappers for Cairo (development files)

### libcairomm-1.0-doc/focal,focal 1.12.2-4build1 all
  - C++ wrappers for Cairo (documentation)

### libcpgplot0/focal 1.1.0-1 amd64
  - CPGPLOT replacement shared lib based on giza

### libfltk-cairo1.3/focal 1.3.4-10build1 amd64
  - Fast Light Toolkit - Cairo rendering layer support

### libghc-cairo-dev/focal 0.13.6.0-1build1 amd64
  - binding to the Cairo library

### libghc-cairo-doc/focal,focal 0.13.6.0-1build1 all
  - Binding to the Cairo library; documentation

### libghc-cairo-prof/focal 0.13.6.0-1build1 amd64
  - Binding to the Cairo library; profiling libraries

### libghc-chart-cairo-dev/focal 1.9.1-1build1 amd64
  - Cairo backend for Charts

### libghc-chart-cairo-doc/focal,focal 1.9.1-1build1 all
  - Cairo backend for Charts; documentation

### libghc-chart-cairo-prof/focal 1.9.1-1build1 amd64
  - Cairo backend for Charts; profiling libraries

### libghc-chart-dev/focal 1.9.1-1build1 amd64
  - library for generating 2D Charts and Plots

### libghc-chart-doc/focal,focal 1.9.1-1build1 all
  - library for generating 2D Charts and Plots; documentation

### libghc-chart-prof/focal 1.9.1-1build1 amd64
  - library for generating 2D Charts and Plots; profiling libraries

### libghc-diagrams-cairo-dev/focal 1.4.1-4build1 amd64
  - Cairo backend for the diagrams drawing EDSL

### ### libghc-diagrams-cairo-doc/focal,focal 1.4.1-4build1 all
  - Cairo backend for the diagrams drawing EDSL; documentation

### libghc-diagrams-cairo-prof/focal 1.4.1-4build1 amd64
  - Cairo backend for the diagrams drawing EDSL; profiling libraries

### libghc-diagrams-dev/focal,focal 1.4-5 all
  - embedded domain-specific language for declarative vector graphics

### libghc-diagrams-doc/focal,focal 1.4-5 all
  - Embedded domain-specific language for declarative vector graphics

### libghc-diagrams-gtk-dev/focal 1.4-6build1 amd64
  - Backend for rendering diagrams directly to GTK windows

### libghc-diagrams-gtk-doc/focal,focal 1.4-6build1 all
  - Backend for rendering diagrams directly to GTK windows; documentation

### libghc-diagrams-gtk-prof/focal 1.4-6build1 amd64
  - Backend for rendering diagrams directly to GTK windows; profiling libraries

### libghc-diagrams-prof/focal,focal 1.4-5 all
  - Embedded domain-specific language for declarative vector graphics

### libghc-gi-cairo-connector-dev/focal 0.0.1-2 amd64
  - GI friendly Binding to the Cairo library

### libghc-gi-cairo-connector-doc/focal,focal 0.0.1-2 all
  - GI friendly Binding to the Cairo library; documentation

### ### libghc-gi-cairo-connector-prof/focal 0.0.1-2 amd64
  - GI friendly Binding to the Cairo library; profiling libraries

### libghc-gi-cairo-dev/focal 1.0.17-1build1 amd64
  - Cairo bindings

### libghc-gi-cairo-doc/focal,focal 1.0.17-1build1 all
  - Cairo bindings; documentation

### libghc-gi-cairo-prof/focal 1.0.17-1build1 amd64
  - Cairo bindings; profiling libraries

### libghc-gi-cairo-render-dev/focal 0.0.1-2 amd64
  - GI friendly Binding to the Cairo library.

### libghc-gi-cairo-render-doc/focal,focal 0.0.1-2 all
  - GI friendly Binding to the Cairo library.; documentation

### libghc-gi-cairo-render-prof/focal 0.0.1-2 amd64
  - GI friendly Binding to the Cairo library.; profiling libraries

### libghc-pango-dev/focal 0.13.6.0-2 amd64
  - binding to the Pango text rendering engine

### libghc-pango-doc/focal,focal 0.13.6.0-2 all
  - Binding to the Pango text rendering engine; documentation

### libghc-pango-prof/focal 0.13.6.0-2 amd64
  - Binding to the Pango text rendering engine; profiling libraries

### libgiza0/focal 1.1.0-1 amd64
  - Lightweight scientific plotting library (shared library)
### 
### libgoocanvas-2.0-9/focal 2.0.4-1 amd64
  - Canvas widget for GTK+ - shared library

### libgoocanvas-2.0-common/focal,focal 2.0.4-1 all
  - Canvas widget for GTK+ - common files

### libgoocanvas-2.0-dev/focal 2.0.4-1 amd64
  - Canvas widget for GTK+ - development files

### libgoocanvas2-perl/focal,focal 0.06-1 all
  - Perl bindings for the goocanvas-2.0 widget using Glib::Object::Introspection

### libgoocanvasmm-2.0-6/focal 1.90.11-3build1 amd64
  - C++ bindings for GooCanvas - shared library

### libgoocanvasmm-2.0-dev/focal 1.90.11-3build1 amd64
  - C++ bindings for GooCanvas - development files

### libgoocanvasmm-2.0-doc/focal,focal 1.90.11-3build1 all
  - C++ bindings for GooCanvas - documentation and examples

### libgraphics-primitive-driver-cairo-perl/focal,focal 0.47-1 all
  - backend providing graphics support using Cairo

### libgtk3.0-cil-dev/focal 2.99.3-4 amd64
  - CLI binding for the GTK+ toolkit 3.0

### libmono-cairo4.0-cil/focal,focal 6.8.0.105+dfsg-2 all
  - Mono Cairo library (for CLI 4.0)

### libpango-perl/focal 1.227-3build1 amd64
  - Perl module to layout and render international text

### libpangocairo-1.0-0/focal,now 1.44.7-2ubuntu4 amd64 [installed,automatic]
  - Layout and rendering of internationalized text

### libpgplot0/focal 1.1.0-1 amd64
  - PGPLOT replacement shared lib based on giza

### libpixman-1-0/focal,now 0.38.4-0ubuntu1 amd64 [installed,automatic]
  - pixel-manipulation library for X and cairo

### libpixman-1-dev/focal,now 0.38.4-0ubuntu1 amd64 [installed,automatic]
  - pixel-manipulation library for X and cairo (development files)

### librust-cairo-rs+dox-dev/focal 0.7.1-1 amd64
  - Rust bindings for the Cairo library - feature "dox"

### librust-cairo-rs+embed-lgpl-docs-dev/focal 0.7.1-1 amd64
  - Rust bindings for the Cairo library - feature "embed-lgpl-docs"

### librust-cairo-rs+glib-dev/focal 0.7.1-1 amd64
  - Rust bindings for the Cairo library - feature "glib"

### librust-cairo-rs+glib-sys-dev/focal 0.7.1-1 amd64
  - Rust bindings for the Cairo library - feature "glib-sys"

### librust-cairo-rs+gobject-sys-dev/focal 0.7.1-1 amd64
  - Rust bindings for the Cairo library - feature "gobject-sys"

### librust-cairo-rs+gtk-rs-lgpl-docs-dev/focal 0.7.1-1 amd64
  - Rust bindings for the Cairo library - feature "gtk-rs-lgpl-docs"

### librust-cairo-rs+pdf-dev/focal 0.7.1-1 amd64
  - Rust bindings for the Cairo library - feature "pdf"

### librust-cairo-rs+png-dev/focal 0.7.1-1 amd64
  - Rust bindings for the Cairo library - feature "png"

### librust-cairo-rs+ps-dev/focal 0.7.1-1 amd64
  - Rust bindings for the Cairo library - feature "ps"

### librust-cairo-rs+purge-lgpl-docs-dev/focal 0.7.1-1 amd64
  - Rust bindings for the Cairo library - feature "purge-lgpl-docs"

### librust-cairo-rs+svg-dev/focal 0.7.1-1 amd64
  - Rust bindings for the Cairo library - feature "svg"

### librust-cairo-rs+use-glib-dev/focal 0.7.1-1 amd64
  - Rust bindings for the Cairo library - feature "use_glib"

### librust-cairo-rs+v1-14-dev/focal 0.7.1-1 amd64
  - Rust bindings for the Cairo library - feature "v1_14"

### librust-cairo-rs+v1-16-dev/focal 0.7.1-1 amd64
  - Rust bindings for the Cairo library - feature "v1_16"

### librust-cairo-rs+xcb-dev/focal 0.7.1-1 amd64
  - Rust bindings for the Cairo library - feature "xcb"

### librust-cairo-rs+xlib-dev/focal 0.7.1-1 amd64
  - Rust bindings for the Cairo library - feature "xlib"

### librust-cairo-rs-dev/focal 0.7.1-1 amd64
  - Rust bindings for the Cairo library - Rust source code

### librust-cairo-sys-rs+dox-dev/focal 0.9.0-2 amd64
  - FFI bindings to libcairo - feature "dox"

### librust-cairo-sys-rs+glib-sys-dev/focal 0.9.0-2 amd64
  - FFI bindings to libcairo - feature "glib-sys"

### librust-cairo-sys-rs+use-glib-dev/focal 0.9.0-2 amd64
  - FFI bindings to libcairo - feature "use_glib"

### librust-cairo-sys-rs+x11-dev/focal 0.9.0-2 amd64
  - FFI bindings to libcairo - feature "x11"

### librust-cairo-sys-rs+xlib-dev/focal 0.9.0-2 amd64
  - FFI bindings to libcairo - feature "xlib"

### librust-cairo-sys-rs-dev/focal 0.9.0-2 amd64
  - FFI bindings to libcairo - Rust source code

### librust-pangocairo+dox-dev/focal 0.8.0-1 amd64
  - Rust bindings for the PangoCairo library - feature "dox"

### librust-pangocairo+embed-lgpl-docs-dev/focal 0.8.0-1 amd64
  - Rust bindings for the PangoCairo library - feature "embed-lgpl-docs"

### librust-pangocairo+gtk-rs-lgpl-docs-dev/focal 0.8.0-1 amd64
  - Rust bindings for the PangoCairo library - feature "gtk-rs-lgpl-docs"

### librust-pangocairo+purge-lgpl-docs-dev/focal 0.8.0-1 amd64
  - Rust bindings for the PangoCairo library - feature "purge-lgpl-docs"

### librust-pangocairo-dev/focal 0.8.0-1 amd64
  - Rust bindings for the PangoCairo library - Rust source code

### librust-pangocairo-sys-dev/focal 0.10.0-1 amd64
  - FFI bindings to libgtk-3 - Rust source code

### libswt-cairo-gtk-4-jni/focal 4.13.0-1 amd64
  - Standard Widget Toolkit for GTK+ Cairo JNI library

### murrine-themes/focal,focal 0.98.11 all
  - themes for gtk2 murrine engine

### pdf2svg/focal 0.2.3-1 amd64
  - converts PDF documents to SVG files (one per page)

### plplot-driver-cairo/focal 5.15.0+dfsg-12ubuntu1 amd64
  - Scientific plotting library (Cairo driver)

### poppler-utils/focal,now 0.86.1-0ubuntu1 amd64 [installed,automatic]
  - PDF utilities (based on Poppler)

### python-cairo/focal 1.16.2-2ubuntu2 amd64
  - Python bindings for the Cairo vector graphics library

### python-cairo-dbg/focal 1.16.2-2ubuntu2 amd64
  - Python bindings for the Cairo vector graphics library (debug extension)

### python-cairo-dev/focal,focal 1.16.2-2ubuntu2 all
  - Python cairo bindings: development files

### python-cairocffi-doc/focal,focal 0.9.0-4 all
  - cffi-based cairo bindings for Python - Documentation

### python-gi-cairo/focal 3.36.0-1 amd64
  - Python Cairo bindings for the GObject library

### python3-cairo/focal,now 1.16.2-2ubuntu2 amd64 [installed,automatic]
  - Python3 bindings for the Cairo vector graphics library

### python3-cairo-dbg/focal 1.16.2-2ubuntu2 amd64
  - Python3 bindings for the Cairo vector graphics library (debug extension)

### python3-cairo-dev/focal,focal 1.16.2-2ubuntu2 all
  - Python3 cairo bindings: development files

### python3-cairo-doc/focal,focal 1.16.2-2ubuntu2 all
  - Python 3 cairo bindings: documentation files

### python3-cairocffi/focal,focal 0.9.0-4 all
  - cffi-based cairo bindings for Python (Python3)

### python3-cairosvg/focal,focal 2.4.2-1 all
  - SVG to PDF/PS/PNG converter based on Cairo (Python3 library)

### python3-gi-cairo/focal,now 3.36.0-1 amd64 [installed,automatic]
  - Python 3 Cairo bindings for the GObject library

### python3-igraph/focal 0.8.0-2build1 amd64
  - High performance graph data structures and algorithms (Python 3)

### r-cran-cairo/focal 1.5-10-1 amd64
  - GNU R graphics device using cairo graphics library

### r-cran-cairodevice/focal 2.28-1 amd64
  - GNU R Cairo/Gtk2 device driver package

### r-cran-freetypeharfbuzz/focal 0.2.5+dfsg-2 amd64
  - GNU R deterministic computation of text box metrics

### ruby-cairo/focal 1.16.5-1build1 amd64
  - Cairo bindings for the Ruby language

### ruby-cairo-gobject/focal 3.4.1-2build1 amd64
  - CairoGObject bindings for the Ruby language

### scour/focal,focal 0.37-4build1 all
  - SVG scrubber and optimizer (CLI and debhelper)

### sndfile-tools/focal 1.03-7.1 amd64
  - Collection of programs for operating on sound files

### spectools/focal 201601r1-1build1 amd64
  - Utilities for using the Wi-Spy USB spectrum analyzer hardware

### tcpflow-nox/focal 1.5.2+repack1-1build2 amd64
  - TCP flow recorder - version without X11 dependencies

### vim-syntax-gtk/focal,focal 20110314-1 all
  - Syntax files to highlight GTK+ keywords in vim

### xdot/focal,focal 1.1-2 all
  - interactive viewer for Graphviz dot files

**Comment by vaxerski** [comment]
there's a list of package names for Ubuntu, yet you still insist on using the Arch names. It's like trying to find words in a french-french dictionary by searching for english words. Please read the wiki.
