### ISSUE TITLE
Unable to set Control_L, Alt_L, Return to spawn my terminal

### ISSUE THREAD

**Issue by DokStook** [vaxerski/Hypr#70]
Here is the line of the config that I used
`bind=Control_L,Alt_L,RETURN,exec,st`

**Comment by vaxerski** [comment]
read the wiki and stop posting idiotic questions. [wiki](https://github.com/vaxerski/Hypr/wiki/Configuring-Hypr)

**Comment by DokStook** [comment]
I have already went trough it. It is not helping me.

**Comment by vaxerski** [comment]
your bind command clearly shows you have no idea how bind commands work, and the wiki does provide information on how they work.

**Comment by DokStook** [comment]
Reading trough the wiki one more time I still can't find what is wrong. I tried also doing combinations like 'CTRLALT' or 'CTRLALTRETURN', etc. I am really struggling to find what is wrong...

**Comment by vaxerski** [comment]
`bind=CTRLALT,RETURN,exec,st`
