### ISSUE TITLE
Unable to install "libgtkmm-3.0-dev" on ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by Julynx** [vaxerski/Hypr#76]
**Please describe the bug**

When installing the dependencies on ubuntu 22.04 LTS detailed in the readme:

`sudo apt install libgtkmm-3.0-dev`

returns:

`libdbus-1-dev : Depends: libdbus-1-3 (= 1.12.20-2ubuntu4) but 1.12.20-3~devacom is to be installed`

Then, attempting to fix it with:

`sudo apt install libdbus-1-3=1.12.20-2ubuntu4`

returns:
```
The following packages will be REMOVED:
  accountsservice apport at-spi2-core avahi-daemon blueman bluez
  brltty colord dbus dbus-bin dbus-daemon dbus-x11 exo-utils
  file-roller fprintd gcp gcr gir1.2-ayatanaappindicator3-0.1
  gir1.2-gtk-3.0 gir1.2-webkit2-4.0 glib-networking:i386
  gnome-keyring gsettings-ubuntu-schemas
  gstreamer1.0-plugins-good:i386 gvfs gvfs-backends gvfs-daemons
  gvfs-fuse gvfs-libs ipp-usb language-selector-common
  libasound2-plugins:i386 libavahi-client3:i386 libcups2:i386
  libdbus-1-3:i386 libdecor-0-plugin-1-cairo:i386 libfaudio0:i386
  libgamemode0:i386 libgtk-3-bin libpam-fprintd libpcap0.8:i386
  libproxy1-plugin-gsettings libpulse0:i386 libsdl2-2.0-0:i386
  libsoup2.4-1:i386 libthunarx-3-0 libwine:i386 libxfce4ui-2-0
  libxfconf-0-3 lutris modemmanager network-manager
  network-manager-config-connectivity-ubuntu network-manager-pptp
  networkd-dispatcher nvidia-settings packagekit packagekit-tools
  pinentry-gnome3 pkexec policykit-1 policykit-1-gnome polkitd
  pulseaudio-module-bluetooth python3-apport python3-keyring
  python3-launchpadlib python3-secretstorage
  python3-software-properties rtkit screen-resolution-extra
  software-properties-common thunar thunar-volman tlp-rdw
  ubuntu-standard udisks2 upower wine32:i386 xdg-desktop-portal
  xdg-desktop-portal-gtk xfconf xorg xserver-xorg yelp
```
which would remove xorg, pulseaudio, grahphics drivers and many other essential packages.

**Steps to reproduce:**

On ubuntu 22.04 run:

`sudo apt install libgtkmm-3.0-dev`

read the terminal output and try to fix it with

`sudo apt install libdbus-1-3=1.12.20-2ubuntu4`

read the terminal output indicating essential system packages to be removed.

**Expected behavior**

The dependencies indicated by the readme for "ubuntu" being properly installed by apt on the latest stable release 22.04 LTS.

**Anything else?**

`make clear && make release`

Fails with:

`No package 'gtkmm-3.0' found`

Attempting to remove or change the library version in the source code results in gtk not being found by C++, failing at:

`#include <gtk/gtk.h>`

**Comment by vaxerski** [comment]
As you can see by the CI status, everything builds properly on ubuntu. Idk what your issue is, but it's likely it's an issue with your system rather than ubuntu.

Install gtkmm then in your preferred way, and if you can't using any way, it's a problem with your system, and not Hypr.

**Comment by Julynx** [comment]
I already have `libgtkmm-3.0-1v5` installed but Hypr asks specifically for `libgtkmm-3.0-dev` which I cannot get installed as shown above on Ubuntu 22.04

As for the info you have on Hypr being buildable on ubuntu. Is that for 22.04? What is the `libgtkmm` specific version installed?

I am going to try to replicate my issue on a clean 22.04 iso with the dependencies as they appear in the Hypr documentation and will get back to you if It doesn't build.

**Comment by Julynx** [comment]
Confirmed it builds on a clean ubuntu 22.04 iso and the issue is a problem of my system.

**Comment by Julynx** [comment]
Closed
