### ISSUE TITLE
How to install on Fedora?

### ISSUE THREAD

**Issue by dark-steveneq** [vaxerski/Hypr#78]
Hello!
I wanted to install Hypr on Fedora 36, but i don't know how lol

**Comment by vaxerski** [comment]
follow the manual building instructions

**Comment by jacknif3** [comment]
These are the packages required to compile under Fedora 35:

`gcc-c++ ninja-build cmake gcc cairo-devel glib2-devel gtkmm30-devel harfbuzz-devel libxcb-devel libxcb libX11-xcb xcb-util-wm-devel xcb-util-wm xcb-util-cursor-devel xcb-util-cursor xcb-util-keysyms-devel xcb-util-keysyms libxcb-devel libxcb xcb-util xcb-util-devel`

@vaxerski can add it to the Wiki if he decides it will be useful for other people.

**Comment by vaxerski** [comment]
thank you, added.
