### ISSUE TITLE
Colors?

### ISSUE THREAD

**Issue by Infinitybeond1** [vaxerski/Hypr#79]
How do the colors work in the config file? since it needs 8 digits i suspected that it was RRGGBBAA format, but when i tried using a valid hex code on the bar i has a lot of transparency which i dont want, i just want it to be a solid color, is there a converter where i can input 6 digit hex codes and convert them into 8 digit ones

**Comment by vaxerski** [comment]
it's ARGB.

**Comment by Infinitybeond1** [comment]
that solved it, thanks!
