### ISSUE TITLE
What happened to the socket files?

### ISSUE THREAD

**Issue by japrogramer** [vaxerski/Hypr#80]
**Please describe the bug**
Hype no longer creates the socket files on /tmp/hypr

**Steps to reproduce:**
From latest release build new install

**Expected behavior**
Previous behavior

**Screenshots**

**Anything else?**

**Log:**
Please attach a log. (paste it into pastebin and paste here the url) The log can be found in a temp file located in /tmp/hypr/hypr.log.

**Coredump:**
If Hypr crashed, please attach a coredump. (paste into pastebind and paste here the url)

How to?

Systemd instructions:
`coredumpctl`
find the last ocurrence of Hypr and note the PID.
`coredumpctl info <PID>`
will print the coredump.
`coredumpctl info <PID> --no-pager | xclip -sel clip`
will copy it to the clipboard.

**Comment by vaxerski** [comment]
it does, in a different location. See the wiki. I've announced it on the discord server a while ago.

**Comment by vaxerski** [comment]
oh shit wait hypr, hypr never made any socket files.
