### ISSUE TITLE
Reload the configuration

### ISSUE THREAD

**Issue by arcolinuxz** [vaxerski/Hypr#92]
Is there a shortcut to reload Hypr?

Super + Shift + R reloads awesome, bspwm etc ...

**Comment by arcolinuxz** [comment]
i know 

can we get a command or something to trigger this

**Comment by vaxerski** [comment]
*other files*?

**Comment by arcolinuxz** [comment]
sxhkd, polybar, conky, networkmanager, bluetooth, ...

there is more in the hypr folder

**Comment by vaxerski** [comment]
okay, but hypr doesnt care about those and reloading wouldnt do anything to them.

**Comment by arcolinuxz** [comment]
well I have added two execs to the hypr.conf

So if I save hypr.conf in an editor it gets reloaded but what if I am NOT in an editor and I change something to the polybar or launch.sh or sxhkd or ... then it would be nice to be able to tell Hypr to reload the hypr.conf as it would load also the two execs.

**Comment by vaxerski** [comment]
there is no `hyprc` utility. you can `touch` the config tho
